---
configuration:
  node_name: "protected-httpbin"
  microgateway:
    - authorize: true
      error_content_type: "text/plain"
      forbidden_response: "forbidden"
      unauthorized_response: "unauthorized"
      forwarded_token_secret: "this is a secret"
      forwarded_token_signature_alg: "HS512"
      pool_count: 1
      pool_size: 10
      max_idle_time: 10
      required_scopes:
        GET: ["test"]
      scheme: "http"
      host: "httpbin"
      port: 80
      uris: ["/anything"]
      strip_uri: true
